"""Full sprite regeneration: re-extract every character/VFX asset from the
source sheets with the current pipeline (v2 magic-wand keyer), then normalize.

For each config, the exact folders it writes are deleted first so no stale
frames with old counts/sizes survive; folders not covered by any config are
left untouched. Fix-configs run after their base config so their overrides
win. Enemies are skipped here (already regenerated by enemies_v2_config).

Run from repo root:  python tools/regen_all_sprites.py
"""
import json
import os
import shutil
import subprocess
import sys

BASE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(BASE)

# (config, extractor) in dependency order; fixes after their base.
PLAN = [
    ("extract_config", "extract_v2.py"),
    ("silver_config_v2", "extract_v2.py"),
    ("dash_config", "extract_v2.py"),
    ("charged_config", "extract_v2.py"),
    ("extraframes_config", "extract_v2.py"),
    ("extraframes3_config", "extract_v2.py"),
    ("transform_config", "extract_v2.py"),
    ("transform2_config", "extract_v2.py"),
    ("awk_teleport_config", "extract_v2.py"),
    ("awakened_combos_config", "extract_v2.py"),
    ("extraframes_fix", "extract_v2.py"),
    ("extraframes3_fix", "extract_v2.py"),
    ("extraframes_walk", "extract_v2.py"),
    ("hilo_config", "extract_v2.py"),
    ("hilo_extra_config", "extract_v2.py"),
    ("hilo_move_fix", "extract_v2.py"),
    # plain photo-sheet locomotion overrides the blue 24fps rows (blue is
    # reserved for charge/finisher/awakened states per art direction)
    ("silver_locomotion_fix", "extract_v2.py"),
    ("silverjumping_config", "extract_v2.py"),  # dedicated jump/landing arc
    # effects keep the original keyer (soft additive glows)
    ("vfx_config", "extract_sprites.py"),
    ("status_vfx_config", "extract_sprites.py"),
]

NORMALIZE = [
    ("Assets/Art/Sprites/Silver", 100, (0.6, 3.0)),
    ("Assets/Art/Sprites/Awakened", 100, (0.6, 3.0)),
    ("Assets/Art/Sprites/Hilo", 92, (0.6, 3.0)),
]

POST = ["extract_hud.py", "extract_hilo_hud.py", "extract_portraits.py"]


def run(args):
    print("+", " ".join(args), flush=True)
    result = subprocess.run([sys.executable] + args, cwd=ROOT,
                            capture_output=True, text=True)
    tail = (result.stdout + result.stderr).strip().splitlines()[-3:]
    for line in tail:
        print("  ", line)
    if result.returncode != 0:
        print(f"!! FAILED ({result.returncode})")
    return result.returncode


def main():
    failures = 0
    for config, extractor in PLAN:
        path = os.path.join(BASE, config + ".json")
        cfg = json.load(open(path))
        # targeted clean: only the folders this config writes
        for sheet in cfg.get("sheets", []):
            out_dir = os.path.normpath(os.path.join(BASE, sheet["out_dir"]))
            for anim in sheet.get("animations", []):
                folder = os.path.join(out_dir, anim["name"])
                if os.path.isdir(folder):
                    shutil.rmtree(folder)
        failures += run([f"tools/{extractor}", "extract", f"tools/{config}.json"]) != 0

    for root, height, clamp in NORMALIZE:
        failures += run(["tools/normalize_sprite_canvases.py", root,
                         "--target-height", str(height),
                         "--clamp", str(clamp[0]), str(clamp[1])]) != 0

    for script in POST:
        failures += run([f"tools/{script}"]) != 0

    print("regen complete," , failures, "failures")
    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
